# Generated by Django 5.0 on 2023-12-18 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogabatch',
            name='name',
        ),
        migrations.AlterField(
            model_name='yogabatch',
            name='yoga_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yoga_batches', to='yoga.yogauser'),
        ),
    ]
